#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/tailscale-loader.sh
    procd_set_param respawn 30 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    /tmp/tailscale --socket=/tmp/tailscale-runtime/tailscaled.sock down 2>/dev/null
    killall tailscaled 2>/dev/null
    killall tailscale.combined 2>/dev/null
}